<?php
require_once __DIR__ . '/../config/CommunityService.php';
$community = new CommunityService();
$userId = (int) ($_SESSION['user_id'] ?? 0);
$memberships = $community->listMemberships($userId);
$flashSuccess = $_SESSION['flash_success'] ?? null; unset($_SESSION['flash_success']);
$flashError = $_SESSION['flash_error'] ?? null; unset($_SESSION['flash_error']);
$createError = $_SESSION['tenant_create_error'] ?? null; unset($_SESSION['tenant_create_error']);
$createOld = $_SESSION['tenant_create_old'] ?? []; unset($_SESSION['tenant_create_old']);
?>
<section class="mb-4"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><span class="mt-eyebrow">Sua comunidade</span><h1 class="mt-page-title mb-2">Olá, <?php echo e($_SESSION['user_name'] ?? ''); ?></h1><p class="mt-subtitle mb-0">Descubra casas, acompanhe pedidos e escolha a área de uma casa à qual você já pertence.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-primary" href="directory.php"><i class="fa-solid fa-map-location-dot me-2"></i>Encontrar uma casa</a><a class="btn btn-outline-primary" href="#nova-casa"><i class="fa-solid fa-house-circle-check me-2"></i>Cadastrar casa</a></div></div></section>
<?php if ($flashSuccess): ?><div class="alert alert-success" role="status"><?php echo e($flashSuccess); ?></div><?php endif; ?>
<?php if ($flashError): ?><div class="alert alert-danger" role="alert"><?php echo e($flashError); ?></div><?php endif; ?>
<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h3 mb-3">Minhas casas e solicitações</h2><?php if ($memberships): ?><div class="row g-3"><?php foreach ($memberships as $membership): ?><div class="col-12 col-md-6 col-xl-4"><article class="border rounded-4 p-3 h-100"><span class="badge <?php echo $membership['status'] === 'Ativo' ? 'text-bg-success' : ($membership['status'] === 'Recusado' ? 'text-bg-secondary' : 'text-bg-warning'); ?> mb-2"><?php echo e($membership['status']); ?></span><h3 class="h5"><?php echo e($membership['nome_exibicao']); ?></h3><p class="small mb-3">Papel: <strong><?php echo e(str_replace(['Assistencia','FilhoDeSanto','Babalorixa','Yalorixa'], ['Assistência','Filho de santo','Babalorixá','Yalorixá'], $membership['papel'])); ?></strong></p><?php if ($membership['status'] === 'Ativo' && $membership['tenant_status'] === 'Ativo'): ?><form method="post" action="select_tenant.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrfToken); ?>"><input type="hidden" name="tenant_id" value="<?php echo (int) $membership['tenant_id']; ?>"><button class="btn btn-outline-primary w-100" type="submit">Acessar área da casa</button></form><?php else: ?><p class="small text-muted mb-0">Acompanhe por aqui. A decisão é comunicada pela casa ou pela administração global quando aplicável.</p><?php endif; ?></article></div><?php endforeach; ?></div><?php else: ?><p class="text-muted mb-0">Você ainda não possui vínculos. Use o diretório para conhecer uma casa e solicitar participação.</p><?php endif; ?></div></section>
<section class="card border-0 shadow-sm" id="nova-casa"><div class="card-body p-4 p-lg-5"><span class="mt-eyebrow">Criar uma casa</span><h2 class="h3">Cadastrar novo terreiro</h2><p class="text-muted">Qualquer pessoa com conta pode iniciar o cadastro. Se você pedir para ser Babalorixá ou Yalorixá e ainda não existir dirigente verificado, o pedido seguirá para análise do administrador global.</p><?php if ($createError): ?><div class="alert alert-danger" role="alert"><?php echo e($createError); ?></div><?php endif; ?><form class="row g-3" method="post" action="tenant_create.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrfToken); ?>"><div class="col-12"><label class="form-label fw-semibold" for="nome_terreiro">Nome da casa</label><input class="form-control form-control-lg" id="nome_terreiro" name="nome_terreiro" value="<?php echo e($createOld['nome_terreiro'] ?? ''); ?>" required></div><div class="col-sm-6"><label class="form-label fw-semibold" for="nacao">Nação ou tradição</label><input class="form-control" id="nacao" name="nacao" value="<?php echo e($createOld['nacao'] ?? ''); ?>" placeholder="Conforme a casa se identifica"></div><div class="col-sm-6"><label class="form-label fw-semibold" for="fundacao">Fundação (opcional)</label><input class="form-control" type="date" id="fundacao" name="fundacao" value="<?php echo e($createOld['fundacao'] ?? ''); ?>"></div><div class="col-12"><label class="form-label fw-semibold" for="papelCriador">Como você participará inicialmente?</label><select class="form-select" id="papelCriador" name="papel"><option value="Colaborador">Pessoa criadora / colaboradora</option><option value="Babalorixa" <?php echo ($createOld['papel'] ?? '') === 'Babalorixa' ? 'selected' : ''; ?>>Quero solicitar reconhecimento como Babalorixá</option><option value="Yalorixa" <?php echo ($createOld['papel'] ?? '') === 'Yalorixa' ? 'selected' : ''; ?>>Quero solicitar reconhecimento como Yalorixá</option></select></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" id="aceiteCriacao" name="aceite_responsabilidade" value="1" required><label class="form-check-label" for="aceiteCriacao">Confirmo que tenho autorização para cadastrar a casa e que compreendo que dados públicos e privados são administrados separadamente.</label></div></div><div class="col-12"><button class="btn btn-primary btn-lg" type="submit">Cadastrar casa</button></div></form></div></section>
